add exit 0

diff --git a/nordvpn-conn b/nordvpn-conn
--- a/nordvpn-conn
+++ b/nordvpn-conn
@@ -1,12 +1,13 @@
 #!/usr/bin/env bash
 
+
 RUN="1 minute"
 END=$(date -ud "$RUN" +%s)
 
 
 # if nordvpn not installed, exit script
 if ! [ -x "$(command -v nordvpn)" ]; then
-    echo 'ERROR: NordVPN is not installed.' >&2
+    echo "ERROR : NordVPN is not installed." >&2
     exit 0
 fi
 
@@ -22,3 +23,4 @@ while [[ $(date -u +%s) -le $END ]]
       continue
     fi
   done
+
